### ISSUE TITLE
License

### ISSUE THREAD

**Issue by picrap** [darrellp/CSFiglets#2]
Hi, i'd like to reuse your source code in an open source project (here on GitHub), and I can't find any license allowing this.
What are your terms?

**Comment by picrap** [comment]
Nevermind, I wrote my own 😄

**Comment by darrellp** [comment]
Terms are feel free to use however you like.  If you stuck my name in that’d be cool but no big deal.  I use GitHub mostly as a store for me so no big claims on code.  If this is coming WAY late I apologize.  Just noticed it on email.  Have a good day!

Darrell

Sent from my iPhone

On Nov 1, 2018, at 3:03 PM, Pascal Craponne <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, i'd like to reuse your source code in an open source project (here on GitHub), and I can't find any license allowing this.
What are your terms?

**Comment by picrap** [comment]
As I said, I wrote my own (here https://github.com/picrap/FIGlet and here https://www.nuget.org/packages/FIGlet-_-lib)... With a license 😉

**Comment by darrellp** [comment]
Ah – cool.  Sorry again for not getting back sooner.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
